### ISSUE TITLE
Folders other than `gwkokab` are also compiling into package

### ISSUE THREAD

**Issue by Qazalbash** [gwkokab/gwkokab#198]
### Check for existing issues

- [X] Completed

### Description

As per the title, `pyproject.toml` needs to be changed.

### What gwkokab version are you using?

nightly

**Comment by Qazalbash** [comment]
### Solution

Move `gwkokab` directory to `src` and change `tool.setuptools.packages` section in `pyproject.toml` to,

```toml
[tool.setuptools.packages]
find = { where = ["src/"] }
```
