### ISSUE TITLE
pre-commit hooks for docs and docstring formatting

### ISSUE THREAD

**Issue by Qazalbash** [gwkokab/gwkokab#320]
`pre-commit-config.yaml` entries.

```yaml
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-directive-colons
        # Detect mistake of rst directive not ending with double colon.
      - id: rst-inline-touching-normal
        # Detect mistake of inline code touching normal text in rst.
      - id: text-unicode-replacement-char
        # Forbid files which have a UTF-8 Unicode replacement character.
  - repo: https://github.com/PyCQA/docformatter
    # using an untagged rev for forward compatibility with pre-commit 4.0
    # see https://github.com/PyCQA/docformatter/issues/289
    # This should be changed back to a tag when (>1.7.5) is released
    rev: 06907d0267368b49b9180eed423fae5697c1e909
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
        args: [--in-place, --config, ./pyproject.toml]
```

`pyproject.toml` entries.

```toml
[tool.docformatter]
# The ``summaries`` are not (yet) 75 characters because the summary lines can't be
# automatically wrapped and must be re-written, which should be done at some point.
recursive = true
wrap-summaries = 84
wrap-descriptions = 84
black = true
syntax = "sphinx"
```
