### ISSUE TITLE
github actions for PR labeling

### ISSUE THREAD

**Issue by Qazalbash** [gwkokab/gwkokab#329]
Standardize pr tilte and automate labeling according to the title.

```yaml
name: Pull request labeler

on:
  pull_request_target:
    types: [opened, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request title
        uses: thehanimo/pr-title-checker@v1.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Label pull request
        uses: release-drafter/release-drafter@v6
        with:
          disable-releaser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

See detailed setup at [pola-rs/polars](https://github.com/pola-rs/polars).
