### ISSUE TITLE
Add New Repo Review, JSON Schema, PyProject, and MyPy Hooks; Update Existing Pre-commit and PyGrep Hooks

### ISSUE THREAD

**Issue by Qazalbash** [gwkokab/gwkokab#336]
New hooks,

```yaml
  - repo: https://github.com/scientific-python/cookie
    rev: 2024.08.19
    hooks:
      - id: sp-repo-review
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.3
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
      - id: check-readthedocs
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.11.2"
    hooks:
      - id: mypy
        files: src
        additional_dependencies:
          - pytest
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.20.2
    hooks:
      - id: validate-pyproject
```

Update hooks,

```yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types: [svg]
      - id: name-tests-test
        args: ["--pytest-test-first"]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
        # Detect mistake of using backticks instead of double colons in rst.
      - id: rst-directive-colons
        # Detect mistake of rst directive not ending with double colon.
      - id: rst-inline-touching-normal
        # Detect mistake of inline code touching normal text in rst.
      - id: text-unicode-replacement-char
        # Forbid files which have a UTF-8 Unicode replacement character.
```
